# Week 5 - Wed Lab (09/30/26) 

This code accompanies activities for the 09/30/26 lab.

**Table of Contents**

1. [Plicker Questions Code](#sec1)
2. [Cosine Similarity Whiteboard Activity - Your Task](#sec2)
3. [Wikipedia country-specific data](#sec3)

<a id="sec1"></a>
## 1. Plicker Questions Code

This code relates to the Question 13 on the Plicker set of questions for today. We will run the code line by line to see what is going on.

In [1]:
from datetime import datetime, timedelta

**Create a new datetime object**

In [2]:
date1 = datetime(2023, 5, 1)
type(date1)

datetime.datetime

**Create a new timedelta object**

In [3]:
delta = timedelta(days=10)
type(delta)

datetime.timedelta

In [4]:
print(delta)

10 days, 0:00:00

**Adding the two objects**

In [5]:
date2 = date1 + delta
print(date2)

2023-05-11 00:00:00

**Why is this possible?**

Let's show all methods / properties of the object:

In [6]:
dir(date1)

['__add__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__radd__',
 '__reduce__',
 '__reduce_ex__',
 '__replace__',
 '__repr__',
 '__rsub__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 'astimezone',
 'combine',
 'ctime',
 'date',
 'day',
 'dst',
 'fold',
 'fromisocalendar',
 'fromisoformat',
 'fromordinal',
 'fromtimestamp',
 'hour',
 'isocalendar',
 'isoformat',
 'isoweekday',
 'max',
 'microsecond',
 'min',
 'minute',
 'month',
 'now',
 'replace',
 'resolution',
 'second',
 'strftime',
 'strptime',
 'time',
 'timestamp',
 'timetuple',
 'timetz',
 'today',
 'toordinal',
 'tzinfo',
 'tzname',
 'utcfromtimestamp',
 'utcnow',
 'utcoffset',
 'utctimetuple',
 'weekday',
 'year']

Let's look up the docstring of the method `__add__`, which is what is called when we use the + operator:

In [7]:
help(date1.__add__)

Help on method-wrapper:

__add__(value, /) unbound datetime.datetime method
    Return self+value.

**Conclusion:** There is a class method that will accept any value type and then act accordingly to figure out how to add that value to the date, if possible.

<a id="sec2"></a>
## 2. Cosine Similarity Whiteboard Activity

This activity was completed by hand, here is how to do it via Python code.

### Inputs for the problem

In [8]:
documents = [
    "Max likes Sam.",    # D1
    "Sam likes Max.",    # D2
    "Max and Sam.",      # D3
    "Winter likes fall." # D4
]

query = "Sam likes winter"

### Step 1: Create vocabulary of all terms

First I will concatenate all strings into one.

In [9]:
allText = " ".join(documents + [query])
print(allText)

Max likes Sam. Sam likes Max. Max and Sam. Winter likes fall. Sam likes winter

I don't want to have punctuation. There are several ways to do that. Let's see some:

#### Method 1: Iterate over the string, leave out punctuations

In [10]:
import string
print(string.punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [11]:
allText_noPunct = "".join([ch for ch in allText if not ch in string.punctuation])
print(allText_noPunct)

Max likes Sam Sam likes Max Max and Sam Winter likes fall Sam likes winter

### Method 2: Use built-in methods

Pythyn's built-in `str` class has many useful methods for translating a set of characters to another one. Let's see the method in action:

In [12]:
allText.translate(str.maketrans("", "", string.punctuation))

'Max likes Sam Sam likes Max Max and Sam Winter likes fall Sam likes winter'

What's going on?

In [13]:
print(str.maketrans("", "", string.punctuation))

{33: None, 34: None, 35: None, 36: None, 37: None, 38: None, 39: None, 40: None, 41: None, 42: None, 43: None, 44: None, 45: None, 46: None, 47: None, 58: None, 59: None, 60: None, 61: None, 62: None, 63: None, 64: None, 91: None, 92: None, 93: None, 94: None, 95: None, 96: None, 123: None, 124: None, 125: None, 126: None}

This means that if the identified character is punctuation, "translate" would translate the character to a '' (replace it with nothing).

We can see that all ASCII Characters from 0-32 and from 65 to 90 are missing, because those characters will be deleted.

Here is what is happening:

```
str.maketrans(from_str, to_str, delete_chars)
#              ^          ^        ^
#           1st arg    2nd arg  3rd arg
```

* 1st argument (""): The characters you want to replace. (Empty string = replace nothing)

* 2nd argument (""): The characters to replace them with. (Empty string = no replacement mapping)

* 3rd argument (string.punctuation): The characters you want to delete entirely.

### Our vocabulary

Here is a Python one-liner that takes our variable `allText_noPunct` and find the unique words in it.

In [14]:
words = set(allText_noPunct.lower().split())
words

{'and', 'fall', 'likes', 'max', 'sam', 'winter'}

In [15]:
voc = sorted(words)
voc

['and', 'fall', 'likes', 'max', 'sam', 'winter']

### YOUR TURN

Write code to implement the other steps of the process shown in Slide 7.

**Show your process before writing any functions.**

**Use markdown to label the three remaining steps.**

### Step 2. Represent each document and the query in the vector space created by these terms

We will manually assign either 0 or 1 to each slot for each vector - 1 represents Yes, the document contains the vocabulary word and 0 represents No.

In [20]:
vectors = [
    [0, 0, 1, 1, 1, 0],
    [0, 0, 1, 1, 1, 0],
    [1, 0, 0, 1, 1, 0],
    [0, 1, 1, 0, 0, 1],
    [0, 0, 1, 0, 1, 1]
]

df = pd.DataFrame(vectors, columns = voc)

In [21]:
df

   and  fall  likes  max  sam  winter
0    0     0      1    1    1       0
1    0     0      1    1    1       0
2    1     0      0    1    1       0
3    0     1      1    0    0       1
4    0     0      1    0    1       1

## Step 3. Calculate the cosine similarity between the query and each document

Cosine similarity is the dot product between the two vectors divided by squared vector 1 times squared vector 2.

Query is "Sam likes winter."

In [22]:
import math

In [24]:
d1_q = (0 + 0 + 1 + 0 + 1 + 0)/(math.sqrt(3) * math.sqrt(3))
d2_q = (0 + 0 + 1 + 0 + 1 + 0)/(math.sqrt(3) * math.sqrt(3))
d3_q = (0 + 0 + 0 + 0 + 1 + 0)/(math.sqrt(3) * math.sqrt(3))
d4_q = (0 + 0 + 0 + 0 + 0 + 1)/(math.sqrt(3) * math.sqrt(3))

## Step 4. Rank the Results

Let's put all the similarity scores in a sorted list:

In [29]:
scores = list([d1_q, d2_q, d3_q, d4_q])
scores

[0.6666666666666667,
 0.6666666666666667,
 0.33333333333333337,
 0.33333333333333337]

In conclusion, by the cosine similarity test, D1 and D2 are most similar to the query.

<a id="sec3"></a>
## 3. Wikipedia Country-Specific Data

If we know the URL of a date, for example:

```
https://analytics.wikimedia.org/published/datasets/country_project_page/2026-09-29.tsv
```

we can use pandas to read the content of the file into a dataframe.

In [16]:
import pandas as pd

url = "https://analytics.wikimedia.org/published/datasets/country_project_page/2026-09-29.tsv"

df = pd.read_csv(url, sep='\t')

df.head()

URLError: <urlopen error [Errno 54] Connection reset by peer>

Why did this happen? Wikimedia didn't like that we didn't identify ourselves. This is why we need to first get data with requests, then read it from pandas.

In [30]:
import pandas as pd
import requests, io

url = "https://analytics.wikimedia.org/published/datasets/country_project_page/2026-09-29.tsv"

headers = {'User-Agent': 'MyDataAnalysisScript/1.0 (contact: wendywellesley@gmail.com)'}
response = requests.get(url, headers=headers)

df = pd.read_csv(io.StringIO(response.text), sep='\t')
df.head()

     Algeria  DZ  ar.wikipedia     3947 Ø°ÙØ§Ø¡_Ø§ØµØ·ÙØ§Ø¹Ù    Q11660  122
0  Argentina  AR  es.wikipedia  3094323             Juana_Viale  Q9016209  115
1  Argentina  AR  es.wikipedia   327209          JosÃ©_Mourinho    Q79983  114
2  Argentina  AR  es.wikipedia  4449701       Copa_Libertadores   Q184795  386
3  Argentina  AR  es.wikipedia    47340          Thomas_Sankara   Q202155  119
4  Argentina  AR  es.wikipedia  5640452         Michael_Jackson     Q2831  177

io.StringIO: turns regular text string into an in-memory file-like object with a .read() method.

The dataframe doesn't have column name. 

**Your task:** Read the README file to find out the column names and add them to the dataframe.

In [35]:
df = pd.read_csv(io.StringIO(response.text), sep='\t', header=None)
df.head()
columns = ['country', 'country-code', 'wiki', 'page_id', 'article', 'qid', 'views']

In [36]:
df.columns = columns

In [37]:
df.head()

,country,country-code,wiki,page_id,article,qid,views
0,Algeria,DZ,ar.wikipedia,3947,Ø°ÙØ§Ø¡_Ø§ØµØ·ÙØ§Ø¹Ù,Q11660,122
1,Argentina,AR,es.wikipedia,3094323,Juana_Viale,Q9016209,115
2,Argentina,AR,es.wikipedia,327209,JosÃ©_Mourinho,Q79983,114
3,Argentina,AR,es.wikipedia,4449701,Copa_Libertadores,Q184795,386
4,Argentina,AR,es.wikipedia,47340,Thomas_Sankara,Q202155,119